/*
 * This file was automatically generated by EvoSuite
 * Mon Dec 16 09:00:58 GMT 2019
 */

package evo.assignment6.framework.targeting;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import assignment6.framework.targeting.GFTargeting;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import robocode.AdvancedRobot;
import robocode.ScannedRobotEvent;
import robocode.robotinterfaces.peer.IBasicRobotPeer;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GFTargeting_ESTest extends GFTargeting_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      IBasicRobotPeer iBasicRobotPeer0 = mock(IBasicRobotPeer.class, new ViolatedAssumptionAnswer());
      doReturn(898.10532478).when(iBasicRobotPeer0).getBodyHeading();
      doReturn((-1.0)).when(iBasicRobotPeer0).getGunHeading();
      doReturn((-1.0)).when(iBasicRobotPeer0).getX();
      doReturn((-1.0)).when(iBasicRobotPeer0).getY();
      advancedRobot0.setPeer(iBasicRobotPeer0);
      GFTargeting gFTargeting0 = new GFTargeting(advancedRobot0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent("jkr^?S])nVP5`6|", 0.0, (-627.0), 5068.73213391919, 20.0, 3.0, true);
      // Undeclared exception!
      try { 
        gFTargeting0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // robocode.robotinterfaces.peer.IBasicRobotPeer$MockitoMock$506434364 cannot be cast to robocode.robotinterfaces.peer.IAdvancedRobotPeer
         //
         verifyException("robocode._AdvancedRadiansRobot", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      IBasicRobotPeer iBasicRobotPeer0 = mock(IBasicRobotPeer.class, new ViolatedAssumptionAnswer());
      doReturn(3.0).when(iBasicRobotPeer0).getBodyHeading();
      doReturn(1371.065268331233).when(iBasicRobotPeer0).getX();
      doReturn(1371.065268331233).when(iBasicRobotPeer0).getY();
      advancedRobot0.setPeer(iBasicRobotPeer0);
      GFTargeting gFTargeting0 = new GFTargeting(advancedRobot0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent((String) null, 3.0, 0.0, 0.0, (-14.7309093), 1963.05428113, true);
      // Undeclared exception!
      try { 
        gFTargeting0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 981
         //
         verifyException("assignment6.framework.targeting.GFTWave", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GFTargeting gFTargeting0 = new GFTargeting((AdvancedRobot) null);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent();
      // Undeclared exception!
      try { 
        gFTargeting0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("assignment6.framework.targeting.GFTargeting", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      IBasicRobotPeer iBasicRobotPeer0 = mock(IBasicRobotPeer.class, new ViolatedAssumptionAnswer());
      doReturn((-454.52432)).when(iBasicRobotPeer0).getBodyHeading();
      doReturn((-454.52432)).when(iBasicRobotPeer0).getX();
      doReturn((-454.52432)).when(iBasicRobotPeer0).getY();
      advancedRobot0.setPeer(iBasicRobotPeer0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent("jkr^?S])nVP5a6|", (-454.52432), (-454.52432), (-454.52432), (-454.52432), (-454.52432));
      GFTargeting gFTargeting0 = new GFTargeting(advancedRobot0);
      // Undeclared exception!
      try { 
        gFTargeting0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -2
         //
         verifyException("assignment6.framework.targeting.GFTWave", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      IBasicRobotPeer iBasicRobotPeer0 = mock(IBasicRobotPeer.class, new ViolatedAssumptionAnswer());
      doReturn(5.0).when(iBasicRobotPeer0).getBodyHeading();
      doReturn(5.0).when(iBasicRobotPeer0).getGunHeading();
      doReturn(5.0).when(iBasicRobotPeer0).getX();
      doReturn(5.0).when(iBasicRobotPeer0).getY();
      advancedRobot0.setPeer(iBasicRobotPeer0);
      GFTargeting gFTargeting0 = new GFTargeting(advancedRobot0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent();
      // Undeclared exception!
      try { 
        gFTargeting0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // robocode.robotinterfaces.peer.IBasicRobotPeer$MockitoMock$506434364 cannot be cast to robocode.robotinterfaces.peer.IAdvancedRobotPeer
         //
         verifyException("robocode._AdvancedRadiansRobot", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      GFTargeting gFTargeting0 = new GFTargeting(advancedRobot0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent();
      // Undeclared exception!
      try { 
        gFTargeting0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
         //
         // You cannot call the getHeadingRadians() method before your run() method is called, or you are using a Robot object that the game doesn't know about.
         //
         verifyException("robocode._RobotBase", e);
      }
  }
}
