/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 18 13:36:10 GMT 2019
 */

package assignment6.framework.movement;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import assignment6.framework.movement.RandomFluidOrbitMovement;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import robocode.AdvancedRobot;
import robocode.Bullet;
import robocode.BulletHitEvent;
import robocode.DeathEvent;
import robocode.HitByBulletEvent;
import robocode.ScannedRobotEvent;
import robocode.robotinterfaces.peer.IBasicRobotPeer;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RandomFluidOrbitMovement_ESTest extends RandomFluidOrbitMovement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      RandomFluidOrbitMovement randomFluidOrbitMovement0 = new RandomFluidOrbitMovement(advancedRobot0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent("b-o`;YQF", 3008, 119.0, 119.0, 119.0, 1173.77);
      // Undeclared exception!
      try { 
        randomFluidOrbitMovement0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
         //
         // You cannot call the getHeadingRadians() method before your run() method is called, or you are using a Robot object that the game doesn't know about.
         //
         verifyException("robocode._RobotBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RandomFluidOrbitMovement randomFluidOrbitMovement0 = new RandomFluidOrbitMovement((AdvancedRobot) null);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent(":wUrJ^*{.I/$SKgQ", 2395.1423268225, 2395.1423268225, (-759.208297353041), 2395.1423268225, 0.0);
      // Undeclared exception!
      try { 
        randomFluidOrbitMovement0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("assignment6.framework.movement.RandomFluidOrbitMovement", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Random.setNextRandom(1824);
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      IBasicRobotPeer iBasicRobotPeer0 = mock(IBasicRobotPeer.class, new ViolatedAssumptionAnswer());
      doReturn(123.86533349808445, 0.0).when(iBasicRobotPeer0).getBodyHeading();
      doReturn(123.86533349808445).when(iBasicRobotPeer0).getX();
      doReturn(91.0).when(iBasicRobotPeer0).getY();
      advancedRobot0.setPeer(iBasicRobotPeer0);
      RandomFluidOrbitMovement randomFluidOrbitMovement0 = new RandomFluidOrbitMovement(advancedRobot0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent("", 764.0, 1824, 764.0, 1824, 1824, true);
      // Undeclared exception!
      try { 
        randomFluidOrbitMovement0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // robocode.robotinterfaces.peer.IBasicRobotPeer$MockitoMock$247717315 cannot be cast to robocode.robotinterfaces.peer.IAdvancedRobotPeer
         //
         verifyException("robocode.AdvancedRobot", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      IBasicRobotPeer iBasicRobotPeer0 = mock(IBasicRobotPeer.class, new ViolatedAssumptionAnswer());
      doReturn(2127.69043, 2127.69043).when(iBasicRobotPeer0).getBodyHeading();
      doReturn((-1059.0)).when(iBasicRobotPeer0).getX();
      doReturn((-1059.0)).when(iBasicRobotPeer0).getY();
      advancedRobot0.setPeer(iBasicRobotPeer0);
      RandomFluidOrbitMovement randomFluidOrbitMovement0 = new RandomFluidOrbitMovement(advancedRobot0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent(" will be 0", 36.0, (-2281.46772), (-2281.46772), 2177.6, 2177.6, false);
      // Undeclared exception!
      try { 
        randomFluidOrbitMovement0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // robocode.robotinterfaces.peer.IBasicRobotPeer$MockitoMock$247717315 cannot be cast to robocode.robotinterfaces.peer.IAdvancedRobotPeer
         //
         verifyException("robocode.AdvancedRobot", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      IBasicRobotPeer iBasicRobotPeer0 = mock(IBasicRobotPeer.class, new ViolatedAssumptionAnswer());
      doReturn(123.86533349808445, 123.86533349808445).when(iBasicRobotPeer0).getBodyHeading();
      doReturn(123.86533349808445).when(iBasicRobotPeer0).getX();
      doReturn(91.0).when(iBasicRobotPeer0).getY();
      advancedRobot0.setPeer(iBasicRobotPeer0);
      RandomFluidOrbitMovement randomFluidOrbitMovement0 = new RandomFluidOrbitMovement(advancedRobot0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent("", 764.0, 1824, 764.0, 1824, 1824, true);
      // Undeclared exception!
      try { 
        randomFluidOrbitMovement0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // robocode.robotinterfaces.peer.IBasicRobotPeer$MockitoMock$247717315 cannot be cast to robocode.robotinterfaces.peer.IAdvancedRobotPeer
         //
         verifyException("robocode.AdvancedRobot", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      RandomFluidOrbitMovement randomFluidOrbitMovement0 = new RandomFluidOrbitMovement(advancedRobot0);
      Bullet bullet0 = new Bullet(0.0, 0.0, 2043.1386623039245, 2043.1386623039245, "T-GO>xm", "T-GO>xm", false, 3008);
      BulletHitEvent bulletHitEvent0 = new BulletHitEvent("T-GO>xm", 0.0, bullet0);
      randomFluidOrbitMovement0.onBulletHit(bulletHitEvent0);
      assertEquals("T-GO>xm", bulletHitEvent0.getName());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      RandomFluidOrbitMovement randomFluidOrbitMovement0 = new RandomFluidOrbitMovement(advancedRobot0);
      Bullet bullet0 = new Bullet(0.0, 0.0, 2043.1386623039245, 2043.1386623039245, "T-GO>xm", "T-GO>xm", false, 3008);
      HitByBulletEvent hitByBulletEvent0 = new HitByBulletEvent(0.0, bullet0);
      randomFluidOrbitMovement0.onHitByBullet(hitByBulletEvent0);
      assertEquals(0, hitByBulletEvent0.getPriority());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      RandomFluidOrbitMovement randomFluidOrbitMovement0 = new RandomFluidOrbitMovement(advancedRobot0);
      DeathEvent deathEvent0 = new DeathEvent();
      randomFluidOrbitMovement0.onDeath(deathEvent0);
      assertEquals(0L, deathEvent0.getTime());
  }
}
