/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 11 16:23:49 GMT 2020
 */

package evo.assignment6.framework.movement;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import assignment6.framework.movement.StopAndGoMovement;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import robocode.AdvancedRobot;
import robocode.Bullet;
import robocode.BulletHitEvent;
import robocode.DeathEvent;
import robocode.HitByBulletEvent;
import robocode.ScannedRobotEvent;
import robocode.robotinterfaces.peer.IBasicRobotPeer;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StopAndGoMovement_ESTest extends StopAndGoMovement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      stopAndGoMovement0.onBulletHit((BulletHitEvent) null);
      stopAndGoMovement0.onBulletHit((BulletHitEvent) null);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      IBasicRobotPeer iBasicRobotPeer0 = mock(IBasicRobotPeer.class, new ViolatedAssumptionAnswer());
      doReturn(1, 3).when(iBasicRobotPeer0).getRoundNum();
      advancedRobot0.setPeer(iBasicRobotPeer0);
      DeathEvent deathEvent0 = new DeathEvent();
      stopAndGoMovement0.onDeath(deathEvent0);
      stopAndGoMovement0.onDeath(deathEvent0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      stopAndGoMovement0.onBulletHit((BulletHitEvent) null);
      Bullet bullet0 = new Bullet(0.0, 1639.0, 1639.0, 0.0, "", "", true, (-514));
      HitByBulletEvent hitByBulletEvent0 = new HitByBulletEvent(0.0, bullet0);
      stopAndGoMovement0.onHitByBullet(hitByBulletEvent0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement((AdvancedRobot) null);
      Bullet bullet0 = new Bullet((-1511.5), (-1511.5), (-1.0), 3.141592653589793, " will be 0.", "oHS.([nAD>", true, 0);
      HitByBulletEvent hitByBulletEvent0 = new HitByBulletEvent(10.0, bullet0);
      stopAndGoMovement0.onHitByBullet(hitByBulletEvent0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent(" will be 0.", (-1511.5), (-1511.5), (-1511.5), 180.0, 3.141592653589793);
      stopAndGoMovement0.setDelta(scannedRobotEvent0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent("", 0.5, 0.5, 0.0, 0.0, 1819.057364, true);
      stopAndGoMovement0.setDelta(scannedRobotEvent0);
  }

  /*
  This automatically generated test fails to compile since it tries to modify private attributes


  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      stopAndGoMovement0.flat = true;
      stopAndGoMovement0.isFlat();
  }
  */

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      Bullet bullet0 = new Bullet((-2081.1248), (-2081.1248), 0.0, (-2081.1248), "+RabipkQ-ZlJZ7C`;{", "+RabipkQ-ZlJZ7C`;{", false, 3259);
      HitByBulletEvent hitByBulletEvent0 = new HitByBulletEvent(0.0, bullet0);
      stopAndGoMovement0.onHitByBullet(hitByBulletEvent0);
      StopAndGoMovement.getLastEnemyEnergy();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      stopAndGoMovement0.onBulletHit((BulletHitEvent) null);
      StopAndGoMovement.getLastEnemyEnergy();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      // Undeclared exception!
      try { 
        stopAndGoMovement0.setDelta((ScannedRobotEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("assignment6.framework.movement.StopAndGoMovement", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent();
      // Undeclared exception!
      try { 
        stopAndGoMovement0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
         //
         // You cannot call the getHeadingRadians() method before your run() method is called, or you are using a Robot object that the game doesn't know about.
         //
         verifyException("robocode._RobotBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      IBasicRobotPeer iBasicRobotPeer0 = mock(IBasicRobotPeer.class, new ViolatedAssumptionAnswer());
      doReturn(0.0).when(iBasicRobotPeer0).getBodyHeading();
      doReturn((long)1).when(iBasicRobotPeer0).getTime();
      doReturn(0.0).when(iBasicRobotPeer0).getX();
      doReturn((-1745.1037126909)).when(iBasicRobotPeer0).getY();
      advancedRobot0.setPeer(iBasicRobotPeer0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent("", 1, 0.0, 1058.77126787414, 0.0, 1, false);
      // Undeclared exception!
      stopAndGoMovement0.onScannedRobot(scannedRobotEvent0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement((AdvancedRobot) null);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent();
      // Undeclared exception!
      try { 
        stopAndGoMovement0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("assignment6.framework.movement.StopAndGoMovement", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      DeathEvent deathEvent0 = new DeathEvent();
      // Undeclared exception!
      try { 
        stopAndGoMovement0.onDeath(deathEvent0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
         //
         // You cannot call the getRoundNum() method before your run() method is called, or you are using a Robot object that the game doesn't know about.
         //
         verifyException("robocode._RobotBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement((AdvancedRobot) null);
      DeathEvent deathEvent0 = new DeathEvent();
      // Undeclared exception!
      try { 
        stopAndGoMovement0.onDeath(deathEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("assignment6.framework.movement.StopAndGoMovement", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      IBasicRobotPeer iBasicRobotPeer0 = mock(IBasicRobotPeer.class, new ViolatedAssumptionAnswer());
      doReturn(21).when(iBasicRobotPeer0).getRoundNum();
      advancedRobot0.setPeer(iBasicRobotPeer0);
      DeathEvent deathEvent0 = new DeathEvent();
      stopAndGoMovement0.onDeath(deathEvent0);
  }

  /*
  These two automatically generated tests fail to compile since they try to modify private attributes

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      StopAndGoMovement.bulletVelocity = 0.0;
      stopAndGoMovement0.flat = true;
      IBasicRobotPeer iBasicRobotPeer0 = mock(IBasicRobotPeer.class, new ViolatedAssumptionAnswer());
      doReturn(0.0).when(iBasicRobotPeer0).getBodyHeading();
      doReturn((long)21).when(iBasicRobotPeer0).getTime();
      doReturn(0.0).when(iBasicRobotPeer0).getX();
      doReturn(0.0).when(iBasicRobotPeer0).getY();
      advancedRobot0.setPeer(iBasicRobotPeer0);
      StopAndGoMovement.bulletVelocity = 70.0;
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent("", 21, 0.0, 1058.77126787414, 0.0, 21, false);
      // Undeclared exception!
      try { 
        stopAndGoMovement0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // robocode.robotinterfaces.peer.IBasicRobotPeer$MockitoMock$870827601 cannot be cast to robocode.robotinterfaces.peer.IAdvancedRobotPeer
         //
         verifyException("robocode._AdvancedRadiansRobot", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      stopAndGoMovement0.flat = true;
      IBasicRobotPeer iBasicRobotPeer0 = mock(IBasicRobotPeer.class, new ViolatedAssumptionAnswer());
      doReturn(0.0).when(iBasicRobotPeer0).getBodyHeading();
      doReturn((long)21).when(iBasicRobotPeer0).getTime();
      doReturn(0.0).when(iBasicRobotPeer0).getX();
      doReturn((-25.205692561851816)).when(iBasicRobotPeer0).getY();
      advancedRobot0.setPeer(iBasicRobotPeer0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent("", 21, 0.0, 1058.77126787414, 0.0, 21, true);
      // Undeclared exception!
      try { 
        stopAndGoMovement0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // robocode.robotinterfaces.peer.IBasicRobotPeer$MockitoMock$870827601 cannot be cast to robocode.robotinterfaces.peer.IAdvancedRobotPeer
         //
         verifyException("robocode._AdvancedRadiansRobot", e);
      }
  }
  */

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      IBasicRobotPeer iBasicRobotPeer0 = mock(IBasicRobotPeer.class, new ViolatedAssumptionAnswer());
      doReturn(0.0).when(iBasicRobotPeer0).getBodyHeading();
      doReturn(2).when(iBasicRobotPeer0).getRoundNum();
      doReturn((long)2).when(iBasicRobotPeer0).getTime();
      doReturn(0.0).when(iBasicRobotPeer0).getX();
      doReturn(0.0).when(iBasicRobotPeer0).getY();
      advancedRobot0.setPeer(iBasicRobotPeer0);
      DeathEvent deathEvent0 = new DeathEvent();
      stopAndGoMovement0.onDeath(deathEvent0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent("", 2, 1.4441296601282287, 1058.77126787414, 0.0, 2, false);
      // Undeclared exception!
      try { 
        stopAndGoMovement0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // robocode.robotinterfaces.peer.IBasicRobotPeer$MockitoMock$870827601 cannot be cast to robocode.robotinterfaces.peer.IAdvancedRobotPeer
         //
         verifyException("robocode._AdvancedRadiansRobot", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      IBasicRobotPeer iBasicRobotPeer0 = mock(IBasicRobotPeer.class, new ViolatedAssumptionAnswer());
      doReturn(0.0).when(iBasicRobotPeer0).getBodyHeading();
      doReturn((long)21).when(iBasicRobotPeer0).getTime();
      doReturn(0.0).when(iBasicRobotPeer0).getX();
      doReturn((-25.205692561851816)).when(iBasicRobotPeer0).getY();
      advancedRobot0.setPeer(iBasicRobotPeer0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent("", 21, 0.0, 1058.77126787414, 0.0, 21, true);
      // Undeclared exception!
      try { 
        stopAndGoMovement0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // robocode.robotinterfaces.peer.IBasicRobotPeer$MockitoMock$870827601 cannot be cast to robocode.robotinterfaces.peer.IAdvancedRobotPeer
         //
         verifyException("robocode._AdvancedRadiansRobot", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Double double0 = new Double(0.0);
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      IBasicRobotPeer iBasicRobotPeer0 = mock(IBasicRobotPeer.class, new ViolatedAssumptionAnswer());
      doReturn(0.0).when(iBasicRobotPeer0).getBodyHeading();
      doReturn(0.0).when(iBasicRobotPeer0).getX();
      doReturn(double0).when(iBasicRobotPeer0).getY();
      advancedRobot0.setPeer(iBasicRobotPeer0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent("assignment6.framework.movement.StopAndGoMovement", 98, 0.0, 98, 0.0, 98, false);
      // Undeclared exception!
      try { 
        stopAndGoMovement0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // robocode.robotinterfaces.peer.IBasicRobotPeer$MockitoMock$870827601 cannot be cast to robocode.robotinterfaces.peer.IAdvancedRobotPeer
         //
         verifyException("robocode._AdvancedRadiansRobot", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement((AdvancedRobot) null);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent();
      double double0 = stopAndGoMovement0.setDelta(scannedRobotEvent0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      boolean boolean0 = stopAndGoMovement0.isFlat();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      double double0 = StopAndGoMovement.getLastEnemyEnergy();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      StopAndGoMovement stopAndGoMovement0 = new StopAndGoMovement(advancedRobot0);
      HitByBulletEvent hitByBulletEvent0 = new HitByBulletEvent(3.141592653589793, (Bullet) null);
      // Undeclared exception!
      try { 
        stopAndGoMovement0.onHitByBullet(hitByBulletEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("robocode.HitByBulletEvent", e);
      }
  }
}
