/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 18 13:32:31 GMT 2019
 */

package evo.assignment6.framework.movement;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import assignment6.framework.movement.WaveSurfingMovement;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import robocode.AdvancedRobot;
import robocode.Bullet;
import robocode.BulletHitEvent;
import robocode.DeathEvent;
import robocode.HitByBulletEvent;
import robocode.ScannedRobotEvent;
import robocode.robotinterfaces.peer.IBasicRobotPeer;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WaveSurfingMovement_ESTest extends WaveSurfingMovement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfingMovement waveSurfingMovement0 = new WaveSurfingMovement(advancedRobot0);
      IBasicRobotPeer iBasicRobotPeer0 = mock(IBasicRobotPeer.class, new ViolatedAssumptionAnswer());
      doReturn(2.0).when(iBasicRobotPeer0).getBodyHeading();
      doReturn(3.141592653589793).when(iBasicRobotPeer0).getRadarHeading();
      doReturn(160.0).when(iBasicRobotPeer0).getVelocity();
      doReturn(2.0).when(iBasicRobotPeer0).getX();
      doReturn(0.05).when(iBasicRobotPeer0).getY();
      advancedRobot0.setPeer(iBasicRobotPeer0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent("B@po!}", (-2983.0), 0.05, 3.141592653589793, 47, (-1146.0), true);
      // Undeclared exception!
      try { 
        waveSurfingMovement0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // robocode.robotinterfaces.peer.IBasicRobotPeer$MockitoMock$1431228255 cannot be cast to robocode.robotinterfaces.peer.IAdvancedRobotPeer
         //
         verifyException("robocode._AdvancedRadiansRobot", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfingMovement waveSurfingMovement0 = new WaveSurfingMovement(advancedRobot0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent("assignment6.framework.movement.AbstractMovement", 100.0, (-3247.8522531541566), 47, 0.0, (-1609.267), true);
      // Undeclared exception!
      try { 
        waveSurfingMovement0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
         //
         // You cannot call the getX() method before your run() method is called, or you are using a Robot object that the game doesn't know about.
         //
         verifyException("robocode._RobotBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      WaveSurfingMovement waveSurfingMovement0 = new WaveSurfingMovement((AdvancedRobot) null);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent("", 100.0, 0.0, 80, 1.0, 0.0, false);
      // Undeclared exception!
      try { 
        waveSurfingMovement0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("assignment6.framework.movement.WaveSurfingMovement", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfingMovement waveSurfingMovement0 = new WaveSurfingMovement(advancedRobot0);
      waveSurfingMovement0.enemyWaves = null;
      HitByBulletEvent hitByBulletEvent0 = new HitByBulletEvent(728.49, (Bullet) null);
      // Undeclared exception!
      try { 
        waveSurfingMovement0.onHitByBullet(hitByBulletEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      WaveSurfingMovement waveSurfingMovement0 = new WaveSurfingMovement((AdvancedRobot) null);
      Bullet bullet0 = new Bullet(160.0, 47, 0.0, 47, "htZ8ZB9CP-hLf!", "", false, 80);
      HitByBulletEvent hitByBulletEvent0 = new HitByBulletEvent(0.0, bullet0);
      waveSurfingMovement0.onHitByBullet(hitByBulletEvent0);
      assertEquals(9167.324722093172, hitByBulletEvent0.getHeading(), 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfingMovement waveSurfingMovement0 = new WaveSurfingMovement(advancedRobot0);
      waveSurfingMovement0.onDeath((DeathEvent) null);
      assertEquals(160.0, WaveSurfingMovement.WALL_STICK, 0.01);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfingMovement waveSurfingMovement0 = new WaveSurfingMovement(advancedRobot0);
      BulletHitEvent bulletHitEvent0 = new BulletHitEvent("robocode.RobotDeathEvent", 100.0, (Bullet) null);
      waveSurfingMovement0.onBulletHit(bulletHitEvent0);
      assertEquals(160.0, WaveSurfingMovement.WALL_STICK, 0.01);
  }
}
